version: '4'
services:
  mysql:
    image: mysql:8.3.0
    restart: always
    container_name: mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: orderservice
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
  mysql-inventory:
    image: mysql:8.3.0
    restart: always
    container_name: mysql-inventory
    ports:
      - '3307:3306'
    expose:
      - '3307'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventoryService
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql-inventory/data:/var/lib/mysql
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db
